# Site settings
title: Kode IV
email: KodeIVteam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 IV young aspiring coders from around the UK. Coding has become a passion to help serve a better purpose for their own business ideas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://KodeIV.me" # the base hostname & protocol for your site
twitter_username: Kode_IV
github_username:  KodeIV

# Build settings
markdown: kramdown
